---
- hosts: webservers
  remote_user: jenkins
  tasks:
     
  - name: Remove Cloud security service container ...
    shell: docker rm -f cloud.security.service
    ignore_errors: yes

  - name: Remove Cloud security service image ...
    shell: docker rmi -f cloud.security.service
    ignore_errors: yes
  
  - name: Create temp folder ...
    shell: mkdir /home/jenkins/cloud.security.service.tmp && mkdir /home/jenkins/cloud.security.service.tmp/logs
    ignore_errors: yes
    
  - name: Copy Cloud security service jar ...
    copy: src=cloud.security.service-1.0.jar dest=/home/jenkins/cloud.security.service.tmp
  
  - name: Copy Cloud security service Dockerfile ...
    copy: src=Dockerfile dest=/home/jenkins/cloud.security.service.tmp
  
  - name: Build Cloud security service image ...
    shell: cd /home/jenkins/cloud.security.service.tmp && docker build -t cloud.security.service .
  
  - name: Run Cloud security service containers...
    shell: docker run -d --name cloud.security.service -p 3089:3089 -e CLOUD.CONFIG.ROOT.PATH=/AppConfig/test -e CLOUD.CONFIG.SERVICE.URL=http://10.39.101.226:3080/GetConfigFile -e CLOUD.CONFIG.SERVICE.AUTH.CODE=config.auth.code:001 -e SERVICE_NAME=cloud.security.service -e SERVICE_TAGS=test --restart=always -v /home/jenkins/cloud.security.service.tmp/logs:/logs cloud.security.service
    
 
 